### ISSUE TITLE
Hello Raphaël

### ISSUE THREAD

**Issue by emmyconfidence** [sundowndev/ama#1]
Great job Raphaël,

I am having problems using PhoneInfoga tool as i only know how to use a python version.

What do i do please after cloning your tool?

Thank you.

**Comment by sundowndev** [comment]
>Support, Bugs & feature requests should be opened on the relevant issue tracker.

https://github.com/sundowndev/PhoneInfoga/issues

**Comment by emmyconfidence** [comment]
Thanks a lot for your help
