### ISSUE TITLE
Help with hack

### ISSUE THREAD

**Issue by gonegirl1979** [sundowndev/ama#7]
Do you hack iPhones foe hire? It isn’t jailbroken. But my ex has stolen and cheated on me. I need proof. It is in his iPhone messages. I need to access the messages and perhaps some social media messages depending on where he is hiding things. Can you help me? I need to do it secretly so he doesn’t hurt me before I accuse him. Looking for someone that can help. I don’t have access to phone or his Apple ID. Only phone number and email address I think is Apple please help

**Comment by sundowndev** [comment]
Just save your time and money, move on
